"""empty message

Revision ID: 48292b308b60
Revises: 
Create Date: 2017-07-28 23:18:09.511996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48292b308b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogpost', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogpost', type_='foreignkey')
    op.drop_column('blogpost', 'owner_id')
    # ### end Alembic commands ###
